CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" integer,
  "user_type_id" integer,
  "name" varchar(30) NOT NULL,
  "first_last_name" varchar(30) NOT NULL,
  "second_last_name" varchar(30) NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "age" integer NOT NULL,
  "phone" varchar(15) NOT NULL,
  "username" varchar(20) UNIQUE NOT NULL,
  "avatar" text NOT NULL,
  "cellphone_verification" bool DEFAULT false,
  "salary" float NOT NULL,
  "deleted" bool DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "passwords" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "value" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "coords" varchar NOT NULL,
  "street" varchar(30) NOT NULL,
  "ext" varchar(30) NOT NULL,
  "city" varchar(30) NOT NULL,
  "state" varchar(30) NOT NULL,
  "zip_code" varchar(5) NOT NULL,
  "country" varchar(30) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "role_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int,
  "module_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "transfers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "invoice" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" integer,
  "user_id" integer,
  "total" float NOT NULL,
  "subtotal" float NOT NULL,
  "shipping" float NOT NULL,
  "taxes" float NOT NULL,
  "description" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "invoice_products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "invoice_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255),
  "stock" integer NOT NULL,
  "price" float NOT NULL,
  "regular_price" float NOT NULL,
  "weight" float NOT NULL,
  "unit" varchar(3) NOT NULL,
  "branch_id" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "branches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255),
  "coords" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "from" integer,
  "quantity" integer NOT NULL,
  "to" integer
);

CREATE TABLE "payroll_periods" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payrolls" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "payroll_period_id" integer,
  "gross_salary" float NOT NULL,
  "net_salary" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "deductions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text,
  "amount" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "bonuses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text,
  "amount" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payroll_deductions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payroll_id" integer,
  "deduction_id" integer,
  "amount" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payroll_bonuses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payroll_id" integer,
  "bonus_id" integer,
  "amount" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("user_type_id") REFERENCES "user_types" ("id");

ALTER TABLE "passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "role_modules" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "role_modules" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("transaction_id") REFERENCES "transfers" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invoice_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "invoice_products" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoice" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("branch_id") REFERENCES "branches" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("from") REFERENCES "branches" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("to") REFERENCES "branches" ("id");

ALTER TABLE "payrolls" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "payrolls" ADD FOREIGN KEY ("payroll_period_id") REFERENCES "payroll_periods" ("id");

ALTER TABLE "payroll_deductions" ADD FOREIGN KEY ("payroll_id") REFERENCES "payrolls" ("id");

ALTER TABLE "payroll_deductions" ADD FOREIGN KEY ("deduction_id") REFERENCES "deductions" ("id");

ALTER TABLE "payroll_bonuses" ADD FOREIGN KEY ("payroll_id") REFERENCES "payrolls" ("id");

ALTER TABLE "payroll_bonuses" ADD FOREIGN KEY ("bonus_id") REFERENCES "bonuses" ("id");